set(LIB_NAME "ispc_texcomp")
set(TARGET_WITH_NAMESPACE "3rdParty::${LIB_NAME}")
set(LIB_PATH ${DEP_DIR}/${LIB_NAME})

set(${LIB_NAME}_INCLUDE_DIR ${LIB_PATH}/include)

if (MSVC)
    set(${LIB_NAME}_DYNAMIC_LIBRARY ${LIB_PATH}/libs/${PLATFORM}/${CMAKE_BUILD_TYPE}/ispc_texcomp.dll)
else()
    set(${LIB_NAME}_DYNAMIC_LIBRARY  ${LIB_PATH}/libs/${PLATFORM}/${CMAKE_CONFIGURATION_TYPES}/ispc_texcomp.dylib)
endif()

set(${LIB_NAME}_LIBRARY_DEBUG ${LIB_PATH}/libs/${PLATFORM}/debug/${CMAKE_STATIC_LIBRARY_PREFIX}ispc_texcomp${CMAKE_STATIC_LIBRARY_SUFFIX})
set(${LIB_NAME}_LIBRARY_RELEASE ${LIB_PATH}/libs/${PLATFORM}/release/${CMAKE_STATIC_LIBRARY_PREFIX}ispc_texcomp${CMAKE_STATIC_LIBRARY_SUFFIX})

set(${LIB_NAME}_LIBRARY
        "$<$<CONFIG:release>:${${LIB_NAME}_LIBRARY_RELEASE}>"
        "$<$<CONFIG:debug>:${${LIB_NAME}_LIBRARY_DEBUG}>")

add_library(${TARGET_WITH_NAMESPACE} INTERFACE IMPORTED GLOBAL)
target_include_directories(${TARGET_WITH_NAMESPACE} INTERFACE ${${LIB_NAME}_INCLUDE_DIR})
target_link_libraries(${TARGET_WITH_NAMESPACE} INTERFACE ${${LIB_NAME}_LIBRARY})

list(APPEND DYN_LIBS ${${LIB_NAME}_DYNAMIC_LIBRARY})
set(${LIB_NAME}_FOUND True)
